runtime: php
env: flex

runtime_config:
  document_root: public

skip_files:
  - .env

env_variables:
  APP_LOG: errorlog
  APP_KEY: base64:yv8XeWLCy4MsOrJEluTQDFUMQ/pKDtGK5i3UNizZwtw=
  STORAGE_DIR: /tmp



